# Generated by Django 6.0.4 on 2026-05-05 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('rin_verify_success', 'RIN Verified'), ('rin_verify_fail', 'RIN Verification Failed'), ('identity_registered', 'Identity Registered'), ('identity_duplicate', 'Duplicate Registration Blocked'), ('keypair_generated', 'Stellar Keypair Generated'), ('onchain_anchor_ok', 'On-Chain Anchor Succeeded'), ('onchain_anchor_fail', 'On-Chain Anchor Failed')], max_length=30)),
                ('identifier_hash', models.CharField(blank=True, default='', help_text='SHA-256 of the identifier used (never store raw PII).', max_length=64)),
                ('stellar_public_key', models.CharField(blank=True, default='', max_length=56)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Audit Log',
                'verbose_name_plural': 'Registration Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
