# Generated by Django 6.0.4 on 2026-05-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_registrationauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amllog',
            name='source_type',
            field=models.CharField(choices=[('wallet', 'Wallet')], max_length=20),
        ),
    ]
