# Generated by Django 6.0.4 on 2026-04-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlienID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(help_text='The Alien ID card number', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('hashed_rin', models.CharField(help_text='SHA-256 hash of the RIN', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alien ID',
                'verbose_name_plural': 'Alien IDs',
            },
        ),
    ]
